---
- name: Install & configure MariaDB on Rocky 9
  hosts: mariadb
  become: true
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-pymysql   # needed by community.mysql modules
    mariadb_cnf: /etc/my.cnf.d/mariadb-server.cnf
  tasks:
    - name: Ensure packages present
      ansible.builtin.dnf:
        name: "{{ mariadb_packages }}"
        state: present

    - name: Bind on all interfaces (optional)
      ansible.builtin.lineinfile:
        path: "{{ mariadb_cnf }}"
        regexp: '^\s*bind-address\s*='
        line: 'bind-address=0.0.0.0'
        insertafter: '^\[mysqld\]'
        backup: yes

    - name: Enable & start MariaDB
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started

    - name: Ensure database exists
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Ensure application user exists with privileges
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: "%"
        priv: "{{ db_name }}.*:ALL"
        state: present
