---
- name: Install & configure MongoDB on Rocky 9
  hosts: mongodb
  become: true
  vars:
    mongodb_repo_name: "mongodb-org-7.0"
    mongodb_repo_baseurl: "https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/"
    mongodb_packages:
      - mongodb-org
      - python3-pymongo  # needed by community.mongodb modules
  tasks:
    - name: Add MongoDB YUM repo
      ansible.builtin.yum_repository:
        name: "{{ mongodb_repo_name }}"
        description: "MongoDB Repository"
        baseurl: "{{ mongodb_repo_baseurl }}"
        gpgcheck: yes
        gpgkey: https://www.mongodb.org/static/pgp/server-7.0.asc
        enabled: yes

    - name: Install MongoDB packages
      ansible.builtin.dnf:
        name: "{{ mongodb_packages }}"
        state: present

    - name: Enable & start mongod
      ansible.builtin.service:
        name: mongod
        enabled: true
        state: started

    # --- Simple user/db creation while authorization is disabled (default) ---
    # For production, you should enable security.authorization and recreate users accordingly.
    - name: Ensure application user exists with readWrite on the app DB
      community.mongodb.mongodb_user:
        database: "{{ db_name }}"
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        roles:
          - role: readWrite
            db: "{{ db_name }}"
        state: present
        login_host: localhost
        login_port: 27017
