---
- name: Install & configure PostgreSQL on Rocky 9
  hosts: all
  become: true
  collections:
    - community.postgresql
  vars:
    pg_packages:
      - postgresql
      - postgresql-server
      - python3-psycopg2  # needed by community.postgresql modules

  tasks:
    - name: Ensure packages present
      ansible.builtin.dnf:
        name: "{{ pg_packages }}"
        state: present

    - name: Initialize database (idempotent)
      ansible.builtin.command: "postgresql-setup --initdb"
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Allow remote connections (optional)
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/data/postgresql.conf
        regexp: "^#?listen_addresses ="
        line: "listen_addresses = '*'"
        backup: yes
      notify: Restart PostgreSQL   # 👈 tell Ansible to restart later if this file changed

    - name: Open pg_hba for md5 (simple example, adjust for your network)
      ansible.builtin.blockinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        marker: "# {mark} ANSIBLE MANAGED RULES"
        block: |
          host    all             all             0.0.0.0/0               md5
          host    all             all             ::/0                    md5
      notify: Restart PostgreSQL   # 👈 same here

    - name: Enable & start PostgreSQL
      ansible.builtin.service:
        name: postgresql
        enabled: true
        state: started

    - name: Ensure database exists
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        state: present

    - name: Ensure application user exists (create role + password)
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        role_attr_flags: LOGIN
        state: present

    - name: Grant ALL privileges on the database to the user
      become: true
      become_user: postgres
      community.postgresql.postgresql_privs:
        type: database
        objs:
          - "{{ db_name }}"
        roles: "{{ db_user }}"
        privs: ALL
        state: present
        login_db: postgres

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted
